import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../images/logo.png";
import Header from "../component/header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Header/>
        {children}
        <footer className='bg-black'>
            <p className='border-b-1 border-white mx-4 pt-4'>. </p>
            <p className='px-4 py-4 flex justify-center  decoration-white text-white'>© {new Date().getFullYear()} Meine Website. Alle Rechte vorbehalten.</p>
        </footer>
        </body>
        </html>
    );
}



